package tracker.controller;

import java.util.Optional;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

import tracker.dao.UserRepository;
import tracker.domain.User;

@Controller // This means that this class is a Controller
@RequestMapping(path="/user") // This means URL's start with /user (after Application path)
public class UserController {
	@Autowired // This means to get the bean called userRepository
	       // Which is auto-generated by Spring, we will use it to handle the data
	private UserRepository userRepository;
	
	@PostMapping(path="/add") // Map ONLY POST Requests
	public @ResponseBody String addNewUser (@RequestBody User user) {
	  userRepository.save(user);
	  return "Saved";
	}
	  
	@DeleteMapping(path="/delete/{id}") // Map ONLY DELETE Requests
	public @ResponseBody String deleteUser (@PathVariable("id") int id) {
		userRepository.deleteById(id);
		return "Deleted";
	}
	
	@GetMapping(path="/{id}") // Map ONLY GET Requests
	public @ResponseBody Optional<User> getUser (@PathVariable("id") int id) {
		System.out.println("getUserStatus id = " + id);
	    return userRepository.findById(id);
	}
	
	@GetMapping(path="/find")
	public @ResponseBody Iterable<Optional<User>> getUserListByLastName (@RequestParam(required = false)  String email, 
			@RequestParam(required = false)  String firstName, @RequestParam String lastName) {
		System.out.println("findUserByLastName = " + lastName);
	    return userRepository.findByLastName(lastName);
	}
	  
	/*@GetMapping(path="/find")
	public @ResponseBody Iterable<Optional<User>> getUserListByEmail (@RequestParam(required = false)  String email, 
			@RequestParam(required = false)  String firstName, @RequestParam(required = false) String lastName) {
		if (email.equalsIgnoreCase(null)) {
			if (firstName.equalsIgnoreCase(null)) {
				if (lastName.equalsIgnoreCase(null)) {
					return userRepository.findAllUsers();
				}
				return userRepository
			}
		}
	    return userRepository.findByEmail(email);
	}*/
	
	@GetMapping(path="/all")
	public @ResponseBody Iterable<User> getAllUsers() {
		// This returns a JSON or XML with the users
		return userRepository.findAll();
	}
	
	@PutMapping(path="/edit/{id}")
	public @ResponseBody String editUser(@PathVariable("id") int id, @RequestBody User editUser) {
		userRepository.findById(id)
		.map(user -> {
			user.setFirstName(editUser.getFirstName());
			user.setLastName(editUser.getLastName());
			user.setEmail(editUser.getEmail());
			user.setStatus(editUser.getStatus());
			return userRepository.save(user);
		});
		
		return "Edited";
	}
}
